### ISSUE TITLE
ambertools.reduce_add_hydrogens

### ISSUE THREAD

**Issue by etweisberg** [bioexcel/biobb_chemistry#4]
There is currently no parameter for bumping, which are part of the native AmberTools reduce program and are necessary sometimes for hydrogens that are skipped due to being too close to other atoms and short bond lengths (as suggested by the warning message in the standard output).

It would be super helpful if this functionality could be added to this wrapper.

**Comment by etweisberg** [comment]
Example of output warning message from reduce program:
```
WARNING: A 221 PL3 O1   H atom too close to  A 221 PL3 C1   by 0.011267A
        you may need to adjust using -METALBump or -NONMETALBump.
```

**Comment by gbayarri** [comment]
Hi, 

We will add in the new release.

Thanks!

**Comment by gbayarri** [comment]
Implemented at:

https://github.com/bioexcel/biobb_chemistry/blob/master/biobb_chemistry/ambertools/reduce_add_hydrogens.py

It will be added to the new release.
