### ISSUE TITLE
Include faster options to generate 3D coordinates with OpenBabel for larger virtual screenings

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_chemistry#5]
I think the current approach is to include the --gen3d flag to generate the minimum energy conformer for a given ligand. It would be very interesting to have access to other faster options as described in [the Open Babel manual](https://open-babel.readthedocs.io/en/latest/3DStructureGen/SingleConformer.html#gen3d), specially in the context of a large virtual screening. 

I don't have a lot of experience on this so correct me if I'm wrong. But I would imagine that the conformational exploration done by AutoDock Vina on the ligand makes the search for the lowest energy conformer before the docking a bit redundant and undesirable to screen very large libraries. 

Thank you! :)

**Comment by gbayarri** [comment]
Hi @PabloNA97 ,

Feel free to open a new PR with the desired flags for the obabel tools.

Best.
