### ISSUE TITLE
Missing Format Options in call to openbabel cause unexpected behaviour

### ISSUE THREAD

**Issue by PabloNA97** [bioexcel/biobb_chemistry#8]
Those Biobb that use openbabel to write molecule should include Format Options to avoid unexpected behaviours. Format Options are described [here](https://openbabel.org/docs/Command-line_tools/babel.html#format-options)

Format-specific input options can be included with with the command line flag -a (followed by the options)
Format-specific output options can be included with with the command line flag -x (followed by the options)

Imagine you have prepared a ligand externally to obtain the correct protonation state and you have it in sdf format. Now you want to use the biobb to convert them to pdbqt before doing the docking with Autodock. Thus you use `babel_convert` with the minimal options, the command that is executed is:

`obabel ligand.sdf -O ligand_new.pdbqt`

However I believe this erases all-non polar hydrogens from the ligand. If one wants to conserve the hydrogens, we should use this instead:

`obabel ligand.sdf -O ligand_new_h.pdbqt -xh`

See [Autodock PDBQT format specific options](https://openbabel.org/docs/FileFormats/AutoDock_PDBQT_format.html) from the open babel documentation.

A similar thing happens if one uses `babel_add_hydrogens` to prepare the ligand using biobb. The ligand that is written in pdbqt format doesn't contain the correct protonation state. As most hydrogen atoms are not wirtten by default. I believe this is relevant as Autodock Vina will use the hydrogen atoms to decide which atoms can be hydrogen bond donors or acceptors, see _[The bound conformation looks reasonable, except for the hydrogens. Why?](https://autodock-vina.readthedocs.io/en/latest/faq.html)_

Versions: 
- biobb_chemistry 4.1.0 
- Python 3.10
- openbabel 3.1.1

**Comment by gbayarri** [comment]
Hi @PabloNA97 

So, what you want is to add two new parameters to the open babel tools (ie fs_input and fs_output) with wich options for each of them? Only the ones specified for Autodock? These are: b, r, c, s, p, h, n.

Or do you need more options? If this is the case, please, specify them.

**Comment by PabloNA97** [comment]
Hi @gbayarri 

Yes I think the format options are needed. Otherwise the hydrogens are not written. Adding those two parameters should work.

I have not checked all possible formats that can be read or written with open babel. Just found this issue with writing pdbqt files. Which is particularly relevant for the usefulness of the biobbs as pdbqt ligands are needed as input for Autodock Vina. Thus, I would start supporting format options for pdbqt at least and consider other cases only if needed. See [here](https://openbabel.org/docs/FileFormats/AutoDock_PDBQT_format.html).

Thanks @gbayarri :)

**Comment by gbayarri** [comment]
Hi @PabloNA97 

The new format-scpecific options for obabel tools are included in the new biobb_chemistry **v4.2.1**.
